// packages/solid/src/provider.tsx
import type { Authorizer } from "@casbinjs/core";
import { createAuthorizer } from "@casbinjs/core";
import { createEffect, createSignal, onCleanup } from "solid-js";
import { CasbinContext } from "./context";
import type { CasbinProviderProps } from "./types";

function createNotReadyError(): Error {
  return new Error("Authorizer is not ready");
}

export function CasbinProvider(props: CasbinProviderProps) {
  const [authorizer, setAuthorizer] = createSignal<Authorizer | null>(props.authorizer ?? null);
  const [isLoading, setIsLoading] = createSignal<boolean>(!props.authorizer && !!props.options);
  const [error, setError] = createSignal<Error | null>(null);

  createEffect(() => {
    const authorizerProp = props.authorizer;
    const options = props.options;

    if (authorizerProp) {
      setAuthorizer(() => authorizerProp);
      setIsLoading(false);
      setError(null);
      return;
    }

    if (!options) {
      setAuthorizer(null);
      setIsLoading(false);
      setError(new Error("CasbinProvider requires either an authorizer or options"));
      return;
    }

    setIsLoading(true);
    setError(null);

    let active = true;
    onCleanup(() => {
      active = false;
    });

    void createAuthorizer(options)
      .then((created) => {
        if (!active) {
          return;
        }

        setAuthorizer(() => created);
        setIsLoading(false);
      })
      .catch((nextError: unknown) => {
        if (!active) {
          return;
        }

        setAuthorizer(null);
        setIsLoading(false);
        setError(nextError instanceof Error ? nextError : new Error("Failed to create authorizer"));
      });
  });

  const value = {
    authorizer,
    isLoading,
    error,
    async can(action: string, resource: string): Promise<boolean> {
      const auth = authorizer();
      if (!auth) {
        return false;
      }

      return auth.can(action, resource);
    },
    async canAny(actions: string[], resource: string): Promise<boolean> {
      const auth = authorizer();
      if (!auth) {
        return false;
      }

      return auth.canAny(actions, resource);
    },
    async canAll(actions: string[], resource: string): Promise<boolean> {
      const auth = authorizer();
      if (!auth) {
        return false;
      }

      return auth.canAll(actions, resource);
    },
    async addPolicy(policy: string[]): Promise<void> {
      const auth = authorizer();
      if (!auth) {
        throw createNotReadyError();
      }

      await auth.addPolicy(policy);
    },
    async removePolicy(policy: string[]): Promise<void> {
      const auth = authorizer();
      if (!auth) {
        throw createNotReadyError();
      }

      await auth.removePolicy(policy);
    },
    async replacePolicies(policies: string[][]): Promise<void> {
      const auth = authorizer();
      if (!auth) {
        throw createNotReadyError();
      }

      await auth.replacePolicies(policies);
    },
    getEnforcer() {
      return authorizer()?.getEnforcer() ?? null;
    },
  };

  return <CasbinContext.Provider value={value}>{props.children}</CasbinContext.Provider>;
}

// packages/react/src/provider.tsx
import type { Authorizer } from '@casbinjs/core';
import { createAuthorizer } from '@casbinjs/core';
import { useEffect, useMemo, useState } from 'react';
import { CasbinContext } from './context';
import type { CasbinProviderProps } from './types';

function createNotReadyError(): Error {
  return new Error('Authorizer is not ready');
}

export function CasbinProvider({
  children,
  authorizer: authorizerProp,
  options,
}: CasbinProviderProps) {
  const [authorizer, setAuthorizer] = useState<Authorizer | null>(authorizerProp ?? null);
  const [isLoading, setIsLoading] = useState<boolean>(!authorizerProp && !!options);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    let active = true;

    if (authorizerProp) {
      setAuthorizer(authorizerProp);
      setIsLoading(false);
      setError(null);
      return () => {
        active = false;
      };
    }

    if (!options) {
      setAuthorizer(null);
      setIsLoading(false);
      setError(new Error('CasbinProvider requires either an authorizer or options'));
      return () => {
        active = false;
      };
    }

    setIsLoading(true);
    setError(null);

    void createAuthorizer(options)
      .then((createdAuthorizer) => {
        if (!active) {
          return;
        }

        setAuthorizer(createdAuthorizer);
        setIsLoading(false);
      })
      .catch((nextError: unknown) => {
        if (!active) {
          return;
        }

        setAuthorizer(null);
        setIsLoading(false);
        setError(nextError instanceof Error ? nextError : new Error('Failed to create authorizer'));
      });

    return () => {
      active = false;
    };
  }, [authorizerProp, options]);

  const value = useMemo(() => {
    return {
      authorizer,
      isLoading,
      error,
      async can(action: string, resource: string): Promise<boolean> {
        if (!authorizer) {
          return false;
        }

        return authorizer.can(action, resource);
      },
      async canAny(actions: string[], resource: string): Promise<boolean> {
        if (!authorizer) {
          return false;
        }

        return authorizer.canAny(actions, resource);
      },
      async canAll(actions: string[], resource: string): Promise<boolean> {
        if (!authorizer) {
          return false;
        }

        return authorizer.canAll(actions, resource);
      },
      async addPolicy(policy: string[]): Promise<void> {
        if (!authorizer) {
          throw createNotReadyError();
        }

        await authorizer.addPolicy(policy);
      },
      async removePolicy(policy: string[]): Promise<void> {
        if (!authorizer) {
          throw createNotReadyError();
        }

        await authorizer.removePolicy(policy);
      },
      async replacePolicies(policies: string[][]): Promise<void> {
        if (!authorizer) {
          throw createNotReadyError();
        }

        await authorizer.replacePolicies(policies);
      },
      getEnforcer() {
        return authorizer?.getEnforcer() ?? null;
      },
    };
  }, [authorizer, error, isLoading]);

  return <CasbinContext.Provider value={value}>{children}</CasbinContext.Provider>;
}
